/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ABS_BUILD_DIR "/home/ars/systemd/.build"

#define ABS_SRC_DIR "/home/ars/systemd"

#define CATALOG_DATABASE "/var/lib/systemd/catalog/database"

#define DEFAULT_HIERARCHY CGROUP_UNIFIED_SYSTEMD

/* default cgroup hierarchy as string */
#define DEFAULT_HIERARCHY_NAME "hybrid"

#define DYNAMIC_UID_MAX 65519

#define DYNAMIC_UID_MIN 61184

#define ENABLE_COMPAT_GATEWAY_HOSTNAME 0

#define ENABLE_UTMP 0

#define FALLBACK_HOSTNAME "localhost"

#define GETTEXT_PACKAGE "systemd"

/* The type of gperf "len" parameter */
#define GPERF_LEN_TYPE size_t

#define HAVE_ACL 0

#define HAVE_AUDIT 0

#define HAVE_BLKID 1

#define HAVE_BPF 0

#define HAVE_CHAR16_T 1

#define HAVE_CHAR32_T 1

#define HAVE_COPY_FILE_RANGE 1

#define HAVE_EXPLICIT_BZERO 1

#define HAVE_FOU_ATTR_REMCSUM_NOPARTIAL 1

#define HAVE_FOU_CMD_GET 1

#define HAVE_FOU_ENCAP_GUE 1

#define HAVE_FRA_UID_RANGE 1

#define HAVE_GCRYPT 0

#define HAVE_GETRANDOM 1

#define HAVE_GETTID 0

#define HAVE_IFA_FLAGS 1

#define HAVE_IFLA_BOND_AD_INFO 1

#define HAVE_IFLA_BRIDGE_VLAN_INFO 1

#define HAVE_IFLA_BRPORT_LEARNING_SYNC 1

#define HAVE_IFLA_BRPORT_PROXYARP 1

#define HAVE_IFLA_BR_VLAN_DEFAULT_PVID 1

#define HAVE_IFLA_GENEVE_LABEL 1

#define HAVE_IFLA_GRE_ENCAP_DPORT 1

#define HAVE_IFLA_INET6_ADDR_GEN_MODE 1

#define HAVE_IFLA_IPTUN_ENCAP_DPORT 1

#define HAVE_IFLA_IPVLAN_FLAGS 1

#define HAVE_IFLA_MACVLAN_FLAGS 1

#define HAVE_IFLA_PHYS_PORT_ID 1

#define HAVE_IFLA_VLAN_PROTOCOL 1

#define HAVE_IFLA_VRF_TABLE 1

#define HAVE_IFLA_VTI_REMOTE 1

#define HAVE_IFLA_VXLAN_GPE 1

#define HAVE_IFLA_VXLAN_REMCSUM_NOPARTIAL 1

#define HAVE_IN6_ADDR_GEN_MODE_STABLE_PRIVACY 1

#define HAVE_IPVLAN_F_PRIVATE 1

#define HAVE_KCMP 0

#define HAVE_KEYCTL 0

#define HAVE_KMOD 1

#define HAVE_LIBCRYPTSETUP 0

#define HAVE_LIBCRYPTSETUP_SECTOR_SIZE 0

#define HAVE_LIBIDN 0

#define HAVE_LIBIDN2 0

#define HAVE_LIBIPTC 0

#define HAVE_LO_FLAGS_PARTSCAN 1

#define HAVE_LZ4 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_NAME_TO_HANDLE_AT 1

#define HAVE_NDA_IFINDEX 1

#define HAVE_PIVOT_ROOT 0

#define HAVE_QRENCODE 0

#define HAVE_REALLOCARRAY 1

#define HAVE_RENAMEAT2 0

#define HAVE_SECCOMP 0

#define HAVE_SECURE_GETENV 1

#define HAVE_SELINUX 1

#define HAVE_SETNS 1

/* bin and sbin directories are separate */
#define HAVE_SPLIT_BIN 1

/* /usr/bin and /bin directories are separate */
#define HAVE_SPLIT_USR 0

#define HAVE_STATX 0

#define HAVE_STRUCT_ETHTOOL_LINK_SETTINGS 1

#define HAVE_STRUCT_FIB_RULE_UID_RANGE 1

#define HAVE_STRUCT_STATX 1

#define HAVE_VXCAN_INFO_PEER 1

#define HAVE_XZ 1

#define HAVE___SECURE_GETENV 0

#define LIBDIR "/usr/lib64"

#define NOBODY_GROUP_NAME "nobody"

#define NOBODY_USER_NAME "nobody"

#define PACKAGE_STRING "systemd 239"

#define PACKAGE_VERSION "239"

#define PKGSYSCONFDIR "/etc/systemd"

#define ROOTLIBDIR "/usr/lib64"

#define ROOTLIBEXECDIR "/usr/lib/systemd"

#define ROOTPREFIX "/usr"

#define SIZEOF_DEV_T 8

#define SIZEOF_GID_T 4

#define SIZEOF_INO_T 8

#define SIZEOF_PID_T 4

#define SIZEOF_RLIM_T 8

#define SIZEOF_TIME_T 8

#define SIZEOF_UID_T 4

#define SYSTEMCTL_BINARY_PATH "/usr/bin/systemctl"

#define SYSTEMD_BINARY_PATH "/usr/lib/systemd/systemd"

#define SYSTEMD_CGROUP_AGENT_PATH "/usr/lib/systemd/systemd-cgroups-agent"

#define SYSTEMD_CRYPTSETUP_PATH "/usr/lib/systemd/systemd-cryptsetup"

#define SYSTEMD_FSCK_PATH "/usr/lib/systemd/systemd-fsck"

#define SYSTEMD_GROWFS_PATH "/usr/lib/systemd/systemd-growfs"

#define SYSTEMD_MAKEFS_PATH "/usr/lib/systemd/systemd-makefs"

#define SYSTEMD_SHUTDOWN_BINARY_PATH "/usr/lib/systemd/systemd-shutdown"

#define SYSTEMD_SLEEP_BINARY_PATH "/usr/lib/systemd/systemd-sleep"

#define SYSTEMD_STDIO_BRIDGE_BINARY_PATH "/usr/bin/systemd-stdio-bridge"

#define SYSTEMD_TTY_ASK_PASSWORD_AGENT_BINARY_PATH "/usr/bin/systemd-tty-ask-password-agent"

#define SYSTEM_CONFIG_UNIT_PATH "/etc/systemd/system"

#define SYSTEM_DATA_UNIT_PATH "/usr/lib/systemd/system"

#define SYSTEM_GENERATOR_PATH "/usr/lib/systemd/system-generators"

#define SYSTEM_GID_MAX 999

#define SYSTEM_UID_MAX 999

#define TIME_EPOCH 1541408692

#define UDEVLIBEXECDIR "/usr/lib/udev"

#define USER_CONFIG_UNIT_PATH "/etc/systemd/user"

#define USER_DATA_UNIT_PATH "/usr/lib/systemd/user"

#define USER_GENERATOR_PATH "/usr/lib/systemd/user-generators"

#define USE_SYS_RANDOM_H 1

#define WANT_LINUX_STAT_H 1

#define _GNU_SOURCE

#define __SANE_USERSPACE_TYPES__

